spin_version = "1"
authors = ["Stefan Weisser <stefan.weisser@gmail.com>"]
description = "Serverless WebAssembly Holiday Computation"
name = "holiday"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "holiday"
source = "target/wasm32-wasi/release/holiday.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
